#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

. /scripts/live-functions

log_begin_msg "Moving mount points"

# live-initramfs script

# Move to the new root filesystem so that programs there can get at it.
if [ ! -d /root/live/image ]
then
	mkdir -p /root/live/image
	mount -n --move /live/image /root/live/image
fi

MOUNTED_ON=$(grep /live/image /proc/mounts 2>/dev/null | cut -f 1 -d " ")
if [ -n "$MOUNTED_ON" ] ; then
   echo " * Mounted live system from $MOUNTED_ON">/dev/console
fi

# aufs2 in 2.6.33 has a regression: directories
# can't be accessed when read for the first the time,
# causing a failure when accessing /var/lib/fai for
# example when booting FAI, this simple workaround solves it
ls /root/* >/dev/null 2>&1

log_end_msg
