#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

. /scripts/live-functions

log_begin_msg "Moving mount points"

# live-initramfs script

# Move to the new root filesystem so that programs there can get at it.
if [ ! -d /root/live/image ]
then
	mkdir -p /root/live/image
	mount -n --move /live/image /root/live/image
fi

MOUNTED_ON=$(grep /live/image /proc/mounts 2>/dev/null | cut -f 1 -d " ")
if [ -n "$MOUNTED_ON" ] ; then
   echo "-> Mounted live system on $MOUNTED_ON">/dev/console
fi

log_end_msg
